name: Build and Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --name="MiniBin-KT" --icon=icons/minibin-kt-full.ico app.py
      env:
        PYTHONIOENCODING: utf-8

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-exe
        path: dist/app.exe

    - name: Scan with VirusTotal
      uses: fabasoad/virustotal-api-action@v1.1.3
      with:
        api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
        file: dist/app.exe
